"""increase password_hash length to 255

Revision ID: 20260222105126
Revises: f758ba792bae
Create Date: 2026-02-22 10:51:26.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260222105126'
down_revision = 'f758ba792bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
                    existing_type=sa.String(length=100),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
                    existing_type=sa.String(length=255),
                    type_=sa.String(length=100),
                    existing_nullable=False)
    # ### end Alembic commands ###
