"""Fix user model fields

Revision ID: 5f0e454a6bba
Revises: 88119112040f
Create Date: 2026-02-24 22:35:53.126256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f0e454a6bba'
down_revision = '88119112040f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_request_date', sa.Date(), nullable=True))
        batch_op.drop_column('last_request_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_request_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_request_date')

    # ### end Alembic commands ###
